# Generated by Django 2.2.9 on 2020-01-17 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0003_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='threads',
            field=models.ManyToManyField(blank=True, related_name='ThreadOrigin', to='threads.Thread'),
        ),
    ]
